# Generated by Django 5.0.7 on 2024-08-31 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_restaurant_created_at_restaurant_updated_at"),
        ("users", "0002_profile_is_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurants",
                to="users.profile",
            ),
            preserve_default=False,
        ),
    ]
