# Generated by Django 5.0.7 on 2024-08-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_restaurant_owner"),
        ("pizza", "0004_pizza_rate_burger"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "burger",
                    models.ManyToManyField(related_name="tags", to="pizza.burger"),
                ),
                (
                    "pizza",
                    models.ManyToManyField(related_name="tags", to="pizza.pizza"),
                ),
            ],
        ),
    ]
