# Generated by Django 5.0.7 on 2024-08-02 20:48

import helper.upload
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "image",
                    models.ImageField(upload_to=helper.upload.upload_pizza_image),
                ),
                (
                    "thick_type",
                    models.CharField(
                        choices=[("thin", "Thin"), ("thick", "Thick")],
                        default="thin",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
