# Generated by Django 5.0.7 on 2024-08-09 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.restaurant",
            ),
            preserve_default=False,
        ),
    ]
