# Generated by Django 5.0.7 on 2024-08-09 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
        ("pizza", "0002_pizza_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pizzas",
                to="home.restaurant",
            ),
        ),
    ]
